
name: python-helloworld-ci

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: |
          VERSION=$(date +%s)
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker build . --file Dockerfile --tag ecakubi/python-helloworld:latest
          docker push ecakubi/python-helloworld:${VERSION}
          

       
